// lessonTypes.ts
export const LessonTypesBySubject: Record<string, string[]> = {
    English: [
      "English Writing Essay I",
      "English Writing Essay II",
      "English Comprehension",
      "Oral Communication",
      "Grammar Workshop",
      "Reading Comprehension",
      "Vocabulary Building",
      "Public Speaking",
      "Debate",
    ],
    Mathematics: [
      "Algebra I",
      "Algebra II",
      "Calculus I",
      "Calculus II",
      "Geometry",
      "Trigonometry",
      "Statistics",
      "Probability",
      "Linear Algebra",
      "Problem Solving",
    ],
    Biology: [
      "Cell Biology",
      "Genetics",
      "Human Anatomy",
      "Plant Biology",
      "Ecology",
      "Microbiology",
      "Evolution",
      "Biochemistry",
      "Lab Experiments",
    ],
    Chemistry: [
      "Organic Chemistry",
      "Inorganic Chemistry",
      "Physical Chemistry",
      "Analytical Chemistry",
      "Lab Experiments",
      "Chemical Reactions",
      "Stoichiometry",
      "Thermodynamics",
    ],
    Physics: [
      "Classical Mechanics",
      "Electromagnetism",
      "Optics",
      "Thermodynamics",
      "Quantum Physics",
      "Relativity",
      "Lab Experiments",
      "Problem Solving",
    ],
    Geography: [
      "Physical Geography",
      "Human Geography",
      "Cartography",
      "Climatology",
      "Geospatial Analysis",
      "Environmental Studies",
    ],
    History: [
      "World History",
      "Ancient Civilizations",
      "Modern History",
      "History of Science",
      "Military History",
      "Cultural History",
    ],
    Literature: [
      "Poetry Analysis",
      "Novel Study",
      "Short Stories",
      "Literary Criticism",
      "Dramatic Literature",
      "Creative Writing",
      "Comparative Literature",
    ],
  };
  